name: Generate

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v1.x"]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Cache Dependencies
        run: deno cache generate.ts

      - name: Generate README
        run: deno run --allow-write generate.ts
        
      - name: Update Repo
        run: |
          git config --global user.name 'xethlyx (automated)'
          git config --global user.email '46338199+xethlyx@users.noreply.github.com'
          git commit -am "Automatic generation"
          git push
